(() => {
'use strict';
const $ = id => document.getElementById(id);
const root = document.getElementById('tool-app');
if (!root) return;
const tool = document.body.dataset.tool;
const field = (id,label,placeholder,tag) => '<label class="block text-sm font-medium">'+label+'<'+(tag||'textarea')+' id="'+id+'" class="mt-2 block w-full rounded-xl border border-slate-300 bg-white p-3 text-sm text-slate-800" placeholder="'+(placeholder||'')+'"></'+(tag||'textarea')+'></label>';
const btn = (id,label,primary) => '<button id="'+id+'" class="rounded-lg '+(primary?'bg-blue-600 text-white':'border border-slate-300')+' px-4 py-2 text-sm font-semibold">'+label+'</button>';
const panel = (title,body) => '<section class="rounded-2xl border border-slate-200 bg-white p-4 shadow-sm"><h2 class="mb-3 font-bold">'+title+'</h2>'+body+'</section>';
const note = '所有处理均在当前浏览器完成。重要数据请及时导出备份。';
const pages = {
'text-diff': {title:'文本对比与差异检查',desc:'逐行比较两份文本，快速定位新增、删除与相同内容。',html:panel('原始文本',field('a','原始版本','粘贴原始文本'))+panel('修改后文本',field('b','修改后版本','粘贴新文本'))+'<div class="flex flex-wrap gap-2">'+btn('run','比较差异',true)+btn('swap','交换文本')+btn('clear','清空')+btn('copy','复制结果')+'</div>'+panel('差异结果','<p id="stats" class="mb-3 text-sm text-slate-500">等待比较</p><div id="out" class="min-h-40 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-3 font-mono text-sm">比较结果将在这里显示。</div>')},
'json-tool': {title:'JSON 格式化与校验',desc:'美化、压缩、校验 JSON，支持复制结果。',html:panel('输入 JSON',field('a','JSON 内容','粘贴 JSON 数据'))+'<div class="flex flex-wrap gap-2">'+btn('pretty','格式化',true)+btn('minify','压缩')+btn('sample','示例')+btn('copy','复制结果')+'</div>'+panel('处理结果','<p id="status" class="mb-2 text-sm"></p><pre id="out" class="min-h-40 overflow-auto whitespace-pre-wrap break-words rounded-xl bg-slate-50 p-3 font-mono text-sm">结果将在这里显示。</pre>')},
'dev-toolbox': {title:'开发者编码工具箱',desc:'Base64、URL 编解码、SHA-256、时间戳、UUID 和随机密码。',html:panel('文本编码',field('a','输入文本','输入文本或编码内容'))+'<div class="flex flex-wrap gap-2">'+btn('b64e','Base64 编码',true)+btn('b64d','Base64 解码')+btn('urle','URL 编码')+btn('urld','URL 解码')+btn('sha','SHA-256')+btn('copy','复制结果')+'</div>'+panel('编码结果','<textarea id="out" rows="3" class="w-full rounded-xl border p-3 font-mono text-sm" readonly></textarea><p id="status" class="mt-2 text-sm text-rose-600"></p>')+panel('时间戳转换','<div class="flex flex-wrap gap-2"><input id="ts" class="min-w-0 flex-1 rounded-lg border p-2" placeholder="Unix 时间戳（秒或毫秒）">'+btn('ts-date','转日期',true)+btn('ts-now','当前时间戳')+'</div><p id="dateout" class="mt-3 break-all text-sm"></p>')+panel('UUID 与随机密码','<div class="flex flex-wrap gap-2">'+btn('uuid','生成 UUID',true)+'<input id="len" type="number" min="8" max="128" value="20" class="w-24 rounded-lg border p-2">'+btn('pwd','生成随机密码')+'</div><p id="misc" class="mt-3 break-all font-mono text-sm"></p>')},
'markdown-editor': {title:'Markdown 编辑器',desc:'轻量写作、实时预览、本地草稿保存与 .md 导出。',html:'<div class="flex flex-wrap gap-2">'+btn('sample','示例',false)+btn('save','保存草稿')+btn('download','导出 .md',true)+btn('clear','清空')+'</div><div class="grid gap-4 lg:grid-cols-2">'+panel('Markdown 源文',field('a','编辑内容','支持标题、列表、引用、粗体和代码'))+panel('实时预览','<article id="out" class="min-h-96 break-words leading-7"></article>')+'</div><p id="status" class="text-sm text-slate-500"></p>'},
'budget': {title:'预算与订阅管理',desc:'记录日常支出、月度预算和会员订阅；数据保存在当前浏览器，可导出备份。',html:panel('月度预算','<div class="flex flex-wrap items-end gap-2"><label class="text-sm">预算金额（元）<input id="budget" type="number" min="0" value="3000" class="mt-1 block rounded-lg border p-2"></label>'+btn('save-budget','保存预算',true)+btn('export','导出 JSON 备份')+'</div><div id="summary" class="mt-3 text-sm"></div>')+'<div class="grid gap-4 lg:grid-cols-2">'+panel('添加支出','<form id="expense-form" class="grid gap-2"><input id="name" required class="rounded-lg border p-2" placeholder="支出项目"><input id="amount" required type="number" min=".01" step=".01" class="rounded-lg border p-2" placeholder="金额（元）"><input id="date" required type="date" class="rounded-lg border p-2"><select id="category" class="rounded-lg border p-2"><option>餐饮</option><option>交通</option><option>购物</option><option>住房</option><option>娱乐</option><option>订阅</option><option>其他</option></select><button class="rounded-lg bg-blue-600 px-4 py-2 text-white">添加支出</button></form><div id="expenses" class="mt-3 space-y-2"></div>')+panel('会员订阅','<form id="sub-form" class="grid gap-2"><input id="subname" required class="rounded-lg border p-2" placeholder="订阅服务名称"><input id="subamount" required type="number" min="0" step=".01" class="rounded-lg border p-2" placeholder="月均费用（元）"><input id="subdate" required type="date" class="rounded-lg border p-2"><button class="rounded-lg bg-blue-600 px-4 py-2 text-white">添加订阅</button></form><div id="subs" class="mt-3 space-y-2"></div>')+'</div><p class="text-xs text-slate-500">'+note+'</p>'},
'color-tool': {title:'配色与取色工具',desc:'HEX/RGB 转换、渐变 CSS 生成、从图片提取常见主色。',html:panel('颜色转换','<div class="flex flex-wrap items-center gap-3"><input id="picker" type="color" value="#2563eb" class="h-12 w-16"><input id="hex" value="#2563eb" class="w-36 rounded-lg border p-2 font-mono"><input id="rgb" readonly class="rounded-lg border bg-slate-50 p-2 font-mono text-sm">'+btn('copy','复制 HEX',true)+'</div><div id="swatch" class="mt-3 h-20 rounded-xl"></div>')+panel('渐变 CSS','<div class="flex flex-wrap gap-4"><label>起始色 <input id="c1" type="color" value="#2563eb"></label><label>结束色 <input id="c2" type="color" value="#8b5cf6"></label></div><div id="gradient" class="mt-3 h-20 rounded-xl"></div><code id="css" class="mt-2 block break-all rounded bg-slate-50 p-2 text-sm"></code>'+btn('copy-css','复制 CSS'))+panel('从图片提取主色','<input id="image" type="file" accept="image/*" class="block"><canvas id="canvas" class="mt-3 hidden max-w-full"></canvas><div id="palette" class="mt-3 grid grid-cols-2 gap-2 sm:grid-cols-5"></div>')},
'batch-qr': {title:'批量二维码生成器',desc:'每行输入一条网址或文本，批量生成二维码并逐个下载 PNG。',html:panel('二维码内容',field('a','每行一条内容','https://example.com\\n纳兰的个人小站'))+'<div class="flex flex-wrap items-end gap-3"><label class="text-sm">尺寸<select id="size" class="mt-1 block rounded-lg border p-2"><option>128</option><option selected>200</option><option>300</option><option>400</option></select></label><label class="text-sm">前景色<input id="fg" type="color" value="#111827" class="mt-1 block h-10 w-14"></label><label class="text-sm">背景色<input id="bg" type="color" value="#ffffff" class="mt-1 block h-10 w-14"></label>'+btn('run','生成二维码',true)+btn('clear','清空')+'</div><p id="status" class="text-sm text-slate-500"></p><div id="out" class="grid gap-4 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4"></div>'},
'favicon-generator': {title:'网站图标与启动图生成器',desc:'上传一张图片，生成 favicon、Apple Touch Icon 和常见尺寸 PNG。',html:panel('上传原图','<input id="image" type="file" accept="image/*" class="block"><div class="mt-3 flex flex-wrap items-center gap-4"><canvas id="canvas" width="128" height="128" class="h-32 w-32 rounded-xl border"></canvas><label class="text-sm">背景色 <input id="bg" type="color" value="#ffffff"></label><label class="text-sm"><input id="fill" type="checkbox"> 填充背景</label></div>')+panel('生成尺寸','<div class="flex flex-wrap gap-2">'+btn('run','生成图标',true)+'</div><p id="status" class="mt-2 text-sm text-slate-500"></p><div id="out" class="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4"></div>')+panel('HTML 引用代码','<pre id="snippet" class="overflow-auto rounded-lg bg-slate-50 p-3 text-sm"></pre>'+btn('copy','复制代码'))}
};
const p=pages[tool]||pages['text-diff'];
document.title=p.title+' - 纳兰工具箱';
root.innerHTML='<p class="mb-5 text-sm text-slate-500">'+p.desc+'</p><div class="space-y-4">'+p.html+'</div>';
const setStatus=(s,ok=true)=>{const el=$('status');if(el){el.textContent=s;el.className='mt-2 text-sm '+(ok?'text-emerald-600':'text-rose-600')}};
const esc=s=>String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const download=(blob,name)=>{const a=document.createElement('a');const u=URL.createObjectURL(blob);a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)};
let budgetData={budget:3000,expenses:[],subs:[]};
if(tool==='text-diff'){
$('run').onclick=()=>{const a=$('a').value.split(/\r?\n/),b=$('b').value.split(/\r?\n/);if((a.length+1)*(b.length+1)>1500000){$('stats').textContent='文本较长，请分段比较';return}const dp=Array.from({length:a.length+1},()=>new Uint32Array(b.length+1));for(let i=a.length-1;i>=0;i--)for(let j=b.length-1;j>=0;j--)dp[i][j]=a[i]===b[j]?dp[i+1][j+1]+1:Math.max(dp[i+1][j],dp[i][j+1]);let i=0,j=0,html=[],add=0,del=0;while(i<a.length||j<b.length){if(i<a.length&&j<b.length&&a[i]===b[j]){html.push('<div class="px-2 py-1">'+esc('  '+a[i])+'</div>');i++;j++}else if(j<b.length&&(i===a.length||dp[i][j+1]>=dp[i+1][j])){html.push('<div class="bg-emerald-100 px-2 py-1 text-emerald-900">+ '+esc(b[j++])+'</div>');add++}else{html.push('<div class="bg-rose-100 px-2 py-1 text-rose-900">− '+esc(a[i++])+'</div>');del++}}$('out').innerHTML=html.join('');$('stats').textContent='新增 '+add+' 行 · 删除 '+del+' 行'};$('swap').onclick=()=>{const x=$('a').value;$('a').value=$('b').value;$('b').value=x};$('clear').onclick=()=>{$('a').value='';$('b').value='';$('out').textContent='';$('stats').textContent='已清空'};
}
if(tool==='json-tool'){
$('pretty').onclick=()=>{try{$('out').textContent=JSON.stringify(JSON.parse($('a').value),null,2);setStatus('✓ JSON 语法正确')}catch(e){setStatus('JSON 格式错误：'+e.message,false)}};$('minify').onclick=()=>{try{$('out').textContent=JSON.stringify(JSON.parse($('a').value));setStatus('✓ 已压缩')}catch(e){setStatus('JSON 格式错误：'+e.message,false)}};$('sample').onclick=()=>{$('a').value=JSON.stringify({name:'纳兰',enabled:true,tools:['文本对比','JSON 格式化'],settings:{theme:'dark'}},null,2);$('pretty').click()};
}
if(tool==='dev-toolbox'){
document.querySelectorAll('button').forEach(b=>{const op=b.id;if(['b64e','b64d','urle','urld','sha'].includes(op))b.onclick=async()=>{try{const s=$('a').value;let v='';if(op==='b64e')v=btoa(unescape(encodeURIComponent(s)));if(op==='b64d')v=decodeURIComponent(escape(atob(s.trim())));if(op==='urle')v=encodeURIComponent(s);if(op==='urld')v=decodeURIComponent(s);if(op==='sha')v=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s)))).map(x=>x.toString(16).padStart(2,'0')).join('');$('out').value=v;setStatus('处理完成')}catch(e){setStatus('输入内容无效或浏览器不支持该操作',false)}}});$('ts-date').onclick=()=>{const n=Number($('ts').value),d=new Date(String($('ts').value).length<=10?n*1000:n);$('dateout').textContent=Number.isFinite(n)&&!Number.isNaN(d.getTime())?d.toLocaleString():'请输入有效时间戳';};$('ts-now').onclick=()=>{$('ts').value=Math.floor(Date.now()/1000);$('ts-date').click()};$('uuid').onclick=()=>{$('misc').textContent=crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>{const r=Math.random()*16|0;return(c==='x'?r:(r&3|8)).toString(16)})};$('pwd').onclick=()=>{const n=Math.min(128,Math.max(8,Number($('len').value)||20)),chars='ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789!@#$%_-+=',a=crypto.getRandomValues(new Uint32Array(n));$('misc').textContent=Array.from(a,x=>chars[x%chars.length]).join('')};
}
if(tool==='markdown-editor'){
const key='nalan-md-draft';$('a').value=localStorage.getItem(key)||'# 开始写作\n\n这是一个轻量 Markdown 编辑器。\n\n- 支持实时预览\n- 支持本地保存\n- 可以导出 Markdown 文件\n\n**加粗文字** 与 ~行内代码~';const inline=s=>s.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>').replace(/~([^~]+)~/g,'<code class="rounded bg-slate-100 px-1">$1</code>').replace(/\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,'<a class="text-blue-600 underline" href="$2" target="_blank" rel="noopener">$1</a>');const render=()=>{let code=false,ul=false,ol=false,html=[];const close=()=>{if(ul){html.push('</ul>');ul=false}if(ol){html.push('</ol>');ol=false}};$('a').value.split(/\r?\n/).forEach(line=>{if(line.startsWith('~~~')){close();html.push(code?'</code></pre>':'<pre class="overflow-auto rounded-lg bg-slate-100 p-3"><code>');code=!code;return}if(code){html.push(esc(line)+'\n');return}if(!line.trim()){close();return}if(/^[-*] /.test(line)){if(ol){html.push('</ol>');ol=false}if(!ul){html.push('<ul class="list-disc pl-6">');ul=true}html.push('<li>'+inline(esc(line.slice(2)))+'</li>');return}if(/^\d+\. /.test(line)){if(ul){html.push('</ul>');ul=false}if(!ol){html.push('<ol class="list-decimal pl-6">');ol=true}html.push('<li>'+inline(esc(line.replace(/^\d+\. /,'')))+'</li>');return}close();const h=line.match(/^(#{1,6})\s+(.*)$/);if(h)html.push('<h'+h[1].length+' class="my-3 font-bold">'+inline(esc(h[2]))+'</h'+h[1].length+'>');else if(line.startsWith('> '))html.push('<blockquote class="border-l-4 border-blue-400 pl-3">'+inline(esc(line.slice(2)))+'</blockquote>');else html.push('<p class="my-2">'+inline(esc(line))+'</p>')});close();if(code)html.push('</code></pre>');$('out').innerHTML=html.join('');$('status').textContent='共 '+$('a').value.length+' 个字符'};$('a').oninput=render;render();$('sample').onclick=()=>{$('a').value='# 我的文章标题\n\n## 一、前言\n\n支持**粗体**、~行内代码~和[链接](https://example.com)。\n\n- 第一项\n- 第二项\n\n> 一段引用\n\n~~~js\nconsole.log("Hello Nalan");\n~~~';render()};$('save').onclick=()=>{localStorage.setItem(key,$('a').value);setStatus('草稿已保存到当前浏览器')};$('download').onclick=()=>download(new Blob([$ ('a').value],{type:'text/markdown;charset=utf-8'}),'文章.md');$('clear').onclick=()=>{if(confirm('确定清空编辑内容？')){$('a').value='';render()}};
}
if(tool==='budget'){
try{budgetData={...budgetData,...JSON.parse(localStorage.getItem('nalan-budget-v1')||'{}')}}catch{}const today=new Date().toISOString().slice(0,10);$('date').value=today;$('subdate').value=today;$('budget').value=budgetData.budget;const money=n=>'¥'+Number(n||0).toLocaleString('zh-CN',{minimumFractionDigits:2,maximumFractionDigits:2});const persist=()=>{localStorage.setItem('nalan-budget-v1',JSON.stringify(budgetData));draw()};const draw=()=>{const month=today.slice(0,7),spent=budgetData.expenses.filter(x=>x.date.startsWith(month)).reduce((s,x)=>s+x.amount,0),subsum=budgetData.subs.reduce((s,x)=>s+x.amount,0);$('summary').textContent='本月支出 '+money(spent)+' / 预算 '+money(budgetData.budget)+' · 订阅月均 '+money(subsum);$('expenses').innerHTML=budgetData.expenses.slice().reverse().map(x=>'<div class="flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-2 text-sm"><span>'+esc(x.name)+' · '+x.date+' · '+esc(x.category)+'</span><span>'+money(x.amount)+' <button data-exp="'+x.id+'" class="ml-2 text-rose-600">删除</button></span></div>').join('')||'<p class="text-sm text-slate-500">暂无支出</p>';$('subs').innerHTML=budgetData.subs.map(x=>'<div class="flex items-center justify-between gap-2 rounded-lg bg-slate-50 p-2 text-sm"><span>'+esc(x.name)+' · 续费 '+x.date+'</span><span>'+money(x.amount)+'/月 <button data-sub="'+x.id+'" class="ml-2 text-rose-600">删除</button></span></div>').join('')||'<p class="text-sm text-slate-500">暂无订阅</p>'};$('save-budget').onclick=()=>{budgetData.budget=Math.max(0,Number($('budget').value)||0);persist()};$('expense-form').onsubmit=e=>{e.preventDefault();budgetData.expenses.push({id:crypto.randomUUID(),name:$('name').value,amount:Number($('amount').value),date:$('date').value,category:$('category').value});e.target.reset();$('date').value=today;persist()};$('sub-form').onsubmit=e=>{e.preventDefault();budgetData.subs.push({id:crypto.randomUUID(),name:$('subname').value,amount:Number($('subamount').value),date:$('subdate').value});e.target.reset();$('subdate').value=today;persist()};document.addEventListener('click',e=>{if(e.target.dataset.exp){budgetData.expenses=budgetData.expenses.filter(x=>x.id!==e.target.dataset.exp);persist()}if(e.target.dataset.sub){budgetData.subs=budgetData.subs.filter(x=>x.id!==e.target.dataset.sub);persist()}});$('export').onclick=()=>download(new Blob([JSON.stringify(budgetData,null,2)],{type:'application/json'}),'预算订阅备份.json');draw();
}
if(tool==='color-tool'){
const toRgb=h=>{h=h.replace('#','');if(!/^[0-9a-f]{6}$/i.test(h))return null;return [0,2,4].map(i=>parseInt(h.slice(i,i+2),16))};const sync=h=>{const r=toRgb(h);if(!r)return;$('hex').value=h.toLowerCase();$('picker').value=h.toLowerCase();$('rgb').value='rgb('+r.join(', ')+')';$('swatch').style.background=h};const grad=()=>{const s='linear-gradient(135deg, '+$('c1').value+', '+$('c2').value+')';$('gradient').style.background=s;$('css').textContent='background: '+s+';'};sync('#2563eb');grad();$('picker').oninput=e=>sync(e.target.value);$('hex').onchange=e=>toRgb(e.target.value)?sync(e.target.value):alert('请输入 #RRGGBB 格式颜色');$('c1').oninput=grad;$('c2').oninput=grad;$('image').onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>{const c=$('canvas'),ctx=c.getContext('2d',{willReadFrequently:true}),scale=Math.min(1,400/im.width,400/im.height);c.width=Math.max(1,Math.round(im.width*scale));c.height=Math.max(1,Math.round(im.height*scale));ctx.drawImage(im,0,0,c.width,c.height);c.classList.remove('hidden');const d=ctx.getImageData(0,0,c.width,c.height).data,m=new Map();for(let i=0;i<d.length;i+=16){if(d[i+3]<128)continue;const k=[d[i],d[i+1],d[i+2]].map(v=>(Math.round(v/32)*32>255?255:Math.round(v/32)*32).toString(16).padStart(2,'0')).join('');m.set(k,(m.get(k)||0)+1)}$('palette').innerHTML=[...m].sort((a,b)=>b[1]-a[1]).slice(0,10).map(([h])=>'<button data-color="#'+h+'" class="overflow-hidden rounded-lg border"><span class="block h-12" style="background:#'+h+'"></span><span class="block p-2 font-mono text-xs">#'+h+'</span></button>').join('')};im.src=URL.createObjectURL(f)};$('palette').onclick=e=>{const b=e.target.closest('[data-color]');if(b)sync(b.dataset.color)};
}
if(tool==='batch-qr'){
$('run').onclick=()=>{if(!window.QRCode){setStatus('二维码组件加载失败，请检查网络后刷新。',false);return}const vals=$('a').value.split(/\r?\n/).map(x=>x.trim()).filter(Boolean);if(!vals.length)return setStatus('请先输入内容。',false);if(vals.length>100)return setStatus('单次最多生成 100 个二维码。',false);$('out').innerHTML='';vals.forEach((v,i)=>{const card=document.createElement('div');card.className='rounded-xl border bg-white p-3 text-center';const qr=document.createElement('div');qr.className='flex justify-center';const label=document.createElement('p');label.className='my-2 break-all text-sm';label.textContent=v.length>100?v.slice(0,100)+'…':v;const b=document.createElement('button');b.className='rounded-lg border px-3 py-2 text-sm';b.textContent='下载 PNG';b.onclick=()=>{const c=qr.querySelector('canvas'),im=qr.querySelector('img'),url=c?c.toDataURL('image/png'):im&&im.src;if(!url)return;const a=document.createElement('a');a.href=url;a.download='二维码-'+(i+1)+'.png';a.click()};card.append(qr,label,b);$('out').append(card);new QRCode(qr,{text:v,width:Number($('size').value),height:Number($('size').value),colorDark:$('fg').value,colorLight:$('bg').value,correctLevel:QRCode.CorrectLevel.M})});setStatus('已生成 '+vals.length+' 个二维码，可逐个下载。')};$('clear').onclick=()=>{$('a').value='';$('out').innerHTML='';setStatus('已清空')};
}
if(tool==='favicon-generator'){
let img=null;const sizes=[16,32,48,64,128,180,192,512];const draw=(c,n)=>{const x=c.getContext('2d');x.clearRect(0,0,n,n);if($('fill').checked){x.fillStyle=$('bg').value;x.fillRect(0,0,n,n)}if(img){const s=Math.min(n/img.width,n/img.height),w=img.width*s,h=img.height*s;x.drawImage(img,(n-w)/2,(n-h)/2,w,h)}};$('image').onchange=e=>{const f=e.target.files[0];if(!f)return;const im=new Image();im.onload=()=>{img=im;draw($('canvas'),128);setStatus('已加载 '+im.width+' × '+im.height+' 图片')};im.src=URL.createObjectURL(f)};$('bg').oninput=()=>draw($('canvas'),128);$('fill').onchange=()=>draw($('canvas'),128);$('run').onclick=()=>{if(!img)return setStatus('请先上传图片。',false);$('out').innerHTML='';sizes.forEach(n=>{const c=document.createElement('canvas');c.width=c.height=n;draw(c,n);const card=document.createElement('div');card.className='rounded-xl border p-3 text-center';const thumb=document.createElement('canvas');thumb.width=thumb.height=Math.min(n,96);thumb.getContext('2d').drawImage(c,0,0,thumb.width,thumb.height);thumb.className='mx-auto max-h-24 max-w-24';const label=document.createElement('p');label.className='my-2 text-sm';label.textContent=n+' × '+n;const b=document.createElement('button');b.className='rounded-lg border px-3 py-2 text-sm';b.textContent='下载 PNG';b.onclick=()=>download(c.toDataURL('image/png').startsWith('data:')?dataURLBlob(c.toDataURL('image/png')):new Blob([]),'favicon-'+n+'.png');card.append(thumb,label,b);$('out').append(card)});$('snippet').textContent='<link rel="icon" href="/favicon-32.png" sizes="32x32">\\n<link rel="apple-touch-icon" href="/favicon-180.png">\\n<link rel="icon" href="/favicon-192.png" sizes="192x192">';setStatus('已生成 '+sizes.length+' 个尺寸，请逐个下载。')};function dataURLBlob(u){const a=u.split(','),m=a[0].match(/:(.*?);/)[1];return new Blob([Uint8Array.from(atob(a[1]),c=>c.charCodeAt(0))],{type:m})}
}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b)return;try{if(b.id==='copy'){const target=$('out')||$('snippet');await navigator.clipboard.writeText(target.value!==undefined?target.value:target.innerText);setStatus('已复制到剪贴板')}if(b.id==='copy-css'){await navigator.clipboard.writeText($('css').textContent);setStatus('CSS 已复制')}}catch{setStatus('复制失败，请手动选择内容复制。',false)}});
})();